language: python
os:
  - linux
  - osx
env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=py36
matrix:
  include:
  - sudo: required
    services:
      - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
  - sudo: required
    services:
      - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
         PRE_CMD=linux32

before_install:
- |
  if [[ $PYTHON && "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew update;
    brew install openssl readline;
    brew outdated pyenv || brew upgrade pyenv;
    brew install pyenv-virtualenv;
    pyenv install $PYTHON;
    export PYENV_VERSION=$PYTHON;
    export PATH="/Users/travis/.pyenv/shims:${PATH}";
    pyenv-virtualenv venv;
    source venv/bin/activate;
    python --version;
  fi;
  echo [distutils]                                  > ~/.pypirc;
  echo index-servers=pypi                          >> ~/.pypirc;
  echo [pypi]                                      >> ~/.pypirc;
  echo repository=https://pypi.python.org/pypi     >> ~/.pypirc;
  echo username=kmike                              >> ~/.pypirc;
  echo password=$PYPIPASSWORD                      >> ~/.pypirc;
  touch .travis_tag;
  if [[ $DOCKER_IMAGE ]]; then
    echo $TRAVIS_TAG > .travis_tag;
    cat ~/.pypirc > .pypirc;
  fi;

install:
- |
  if [[ $DOCKER_IMAGE ]]; then
    docker pull $DOCKER_IMAGE &&
    docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/.manylinux-install.sh;
    exit;
  else
    pip install --upgrade pip;
    pip install -r requirements-doc.txt;
    pip install tox;
    pip install -U cython;
  fi;

script:
- ./update_cpp.sh
- tox

after_success:
- pip install wheel twine 
- if [[ $TRAVIS_TAG && "$TRAVIS_OS_NAME" == "osx" ]]; then
  python -W ignore setup.py bdist_wheel;
  twine upload dist/*;
  fi;
- if [[ $TRAVIS_TAG && "$TRAVIS_OS_NAME" == "linux" ]]; then
  python -W ignore setup.py sdist;
  twine upload dist/*;
  fi;

env:
  global:
  - secure: PYPIPASSWORD=yourpypipassword